export const FAVORITE_SET_REQUESTED = 'FAVORITE_SET_REQUESTED';
export const FAVORITE_SET_SUCCEEDED = 'FAVORITE_SET_SUCCEEDED';
export const FAVORITE_SET_FAILED = 'FAVORITE_SET_FAILED';

export const FAVORITE_UNSET_REQUESTED = 'FAVORITE_UNSET_REQUESTED';
export const FAVORITE_UNSET_SUCCEEDED = 'FAVORITE_UNSET_SUCCEEDED';
export const FAVORITE_UNSET_FAILED = 'FAVORITE_UNSET_FAILED';
